export const GET_DATA_REQUEST= 'GET_DATA_REQUEST'
export const GET_DATA_SUCCESS= 'GET_DATA_SUCCESS'
export const GET_DATA_FAILURE= 'GET_DATA_FAILURE'


// export const POST_TODO_REQUEST= 'POST_TODO_REQUEST'
// export const POST_TODO_SUCCESS= 'POST_TODO_SUCCESS'
// export const POST_TODO_FAILURE= 'POST_TODO_FAILURE'