const  Categories=[
{
    line:"/Electronics",
    title:"Consumer Electronics",
    title1:"Smart Electronics",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]


},
{
    line:"Industrical",
    title:"Industrical and Scientific",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Cellphon",
    title:"Cellphon and Accessories",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Appliances",
    title:"Appliances",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Outdors,Fitness,Sports",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Computer",
    title:"Computer,tablet,office",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Heath and Personal Care",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Home Improvement and Tools",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Drone,Toys and Hobbies",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Home and Garden",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Motar and  cars electronics",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Men's Fashion",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Watches and jewelry",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},
{
    line:"Sports",
    title:"Gearbest Promotion",
    arr1:["Smart Watch","Smart watch phon","Wreast band","Smart Watch accessories","Smart Sport watch","Smart Health Watch"],
    title2:"Headphons and Earphons",
    arr2:["Bluetooth Headphons","Gaming Headphons","OverEars Headphons","Earbuds Headphons"],
    title3:"Hot Brands",
    arr3:["Kospet","Lenovo","Corn","KZ","Ticwatch","Goccoma"],
    title4:"Security and Protection",
    arr4:["Access Control","Alarm System","Door Inercoms","Ip Camera","Smart Doorsbells","Camera System"],
    title5:"Xiaome Ecosysytem Products",
    arr5:["Xiaome","Amazfit","Aquara","Haylou","QCY"],
    title6:"Other Consumer electronics",
    arr6:["Smart Homes","Action camera","Gimble","Video Game","Speaker","Microphon"]
},






]

export default Categories